# Generated by Django 3.2.8 on 2021-12-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cost',
        ),
        migrations.AddField(
            model_name='dish',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
