# Generated by Django 3.2.8 on 2021-12-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20211220_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
